include:
- ./function/get-asthma-avg.py
kind: ArchiveUploadSpec
name: function-get-asthma-avg-py-fH2E

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-asthma-avg-fb84e4f5-5836-47b6-9069-6734e306b4bd
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://function-get-asthma-avg-py-fH2E
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-21T13:19:27Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-asthma-avg
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: get-asthma-avg-fb84e4f5-5836-47b6-9069-6734e306b4bd
      namespace: ""
  requestsPerPod: 1
  resources: {}
