include:
- ./function/get-population-list.py
kind: ArchiveUploadSpec
name: function-get-population-list-py-ZHFq

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-population-list-3e82ddd1-d57a-4f07-8fc4-57fb3889925c
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://function-get-population-list-py-ZHFq
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-20T05:36:25Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-population-list
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: get-population-list-3e82ddd1-d57a-4f07-8fc4-57fb3889925c
      namespace: ""
  requestsPerPod: 1
  resources: {}
