include:
- ./function/get-map-region-info.py
kind: ArchiveUploadSpec
name: function-get-map-region-info-py-uk7X

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-map-region-info-87b45aa7-e2e9-4b23-8f3e-fee37a3ad8bd
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://function-get-map-region-info-py-uk7X
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-17T13:09:06Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-map-region-info
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: get-map-region-info-87b45aa7-e2e9-4b23-8f3e-fee37a3ad8bd
      namespace: ""
  requestsPerPod: 1
  resources: {}
