include:
- ./health.py
kind: ArchiveUploadSpec
name: health-py-iKwk

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: health-5fa8b968-0dd6-4e76-b9e1-e8cec443bdd4
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://health-py-iKwk
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-12T05:07:26Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: health
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: health-5fa8b968-0dd6-4e76-b9e1-e8cec443bdd4
      namespace: ""
  requestsPerPod: 1
  resources: {}
