include:
- ./function/get-population-list.py
kind: ArchiveUploadSpec
name: function-get-population-list-py-Dig7

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-population-list-7472a148-8bec-475a-9e27-ad1b1b0a5a03
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://function-get-population-list-py-Dig7
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2024-05-13T21:06:17Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-population-list
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: get-population-list-7472a148-8bec-475a-9e27-ad1b1b0a5a03
      namespace: ""
  requestsPerPod: 1
  resources: {}
