apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: mastodon-data
data:
    MASTODON_URL: 'https://elasticsearch-master.elastic.svc.cluster.local:9200/mastodon/_search'
    MASTODON_COUNT_URL: 'https://elasticsearch-master.elastic.svc.cluster.local:9200/mastodon/_count'
    MASTODON_REQ_BODY_LT:  '{
      "size" : 0,
      "query": {
          "bool": {
              "filter": {
                  "range": {
                      "sentiment_score": {
                          "lt": 0
                      }
                  }
              }
          }
      },
      "_source": "topics",
      "aggs": {
          "topics_count": {
              "terms": {
                  "field": "topics",
                  "size": 1000
              }
          }
      }}'

    MASTODON_REQ_BODY_GT:  '{
      "size" : 0,
      "query": {
          "bool": {
              "filter": {
                  "range": {
                      "sentiment_score": {
                          "gt": 0
                      }
                  }
              }
          }
      },
      "_source": "topics",
      "aggs": {
          "topics_count": {
              "terms": {
                  "field": "topics",
                  "size": 1000
              }
          }
      }}'
