apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: twitter-data
data:
    TWITTER_URL: 'https://elasticsearch-master.elastic.svc.cluster.local:9200/twitter/_search'
    TWITTER_COUNT_URL: 'https://elasticsearch-master.elastic.svc.cluster.local:9200/twitter/_count/'
    TWITTER_REQ_BODY_LT: |
      {
        "query": {
          "bool": {
            "filter": {
              "range": {
                "sentiment": {
                  "gt": 0
                }
              }
            }
          }
        },
        "_source": "topics",
        "aggs": {
          "split_values": {
            "terms": {
              "field": "topics",
              "size": 10000
            }
          }
        }
      }

    TWITTER_REQ_BODY_GT: |
      {
        "query": {
          "bool": {
            "filter": {
              "range": {
                "sentiment": {
                  "gt": 0
                }
              }
            }
          }
        },
        "_source": "topics",
        "aggs": {
          "split_values": {
            "terms": {
              "field": "topics",
              "size": 10000
            }
          }
        }
      }
    
    TWITTER_REQ_BODY_AVG_SENTIMENT: |
      {
        "size": 0,
        "aggs": {
          "regions": {
            "terms": {
              "field": "geo"
            },
            "aggs": {
              "avg_sentiment": {
                "avg": {
                  "field": "sentiment"
                }
              }
            }
          }
        }
      }
