apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: flask_docker
        ports:
        - containerPort: 5000
        env:
        - name: ELASTICSEARCH_URL
          value: 'https://127.0.0.1:9200'
        - name: ELASTICSEARCH_USERNAME
          value: 'elastic'
        - name: ELASTICSEARCH_PASSWORD
          value: 'elastic'
        
        resources:
          limits:
            cpu: "0.5"  # Maximum CPU limit for the container (e.g., 0.5 CPU cores)
            memory: "512Mi"  # Maximum memory limit for the container (e.g., 512 MB)
          requests:
            cpu: "0.1"  # Minimum CPU request for the container (e.g., 0.1 CPU cores)
            memory: "256Mi"  # Minimum memory request for the container (e.g., 256 MB)